#!/bin/bash

# Modules to build
modules='virtualmin-mailman
virtualmin-nginx
virtualmin-awstats
virtualmin-registrar
virtualmin-git
virtualmin-dav
virtualmin-sqlite
virtualmin-slavedns
virtualmin-powerdns
virtualmin-password-recovery
virtualmin-htpasswd
virtualmin-google-analytics
virtualmin-disable
virtualmin-nginx-ssl
virtualmin-notes
virtualmin-vsftpd
virtualmin-signup
virtualmin-oracle
virtualmin-multi-login
virtualmin-mailrelay
virtualmin-init
virtualmin-iframe
ruby-gems'

cd $HOME/build/
for m in $modules; do
  if [ ! -d $m ]; then
    git clone "git@github.com:virtualmin/$m.git"
    cd $m
  else
    cd $m
    git pull
  fi
  tag_ver=$(git describe --tags --abbrev=0)
  if [[ $tag_ver != v* ]]; then
    # No tagged version, skipping
    continue
  fi
  ver=$(echo $tag_ver |sed 's/v//')
  old_ver=$(cat "$HOME/build/lastvers/$m")
  if [ $(echo $ver'>'$old_ver | bc -l) == 1 ]; then
    echo "Newer version found, building."
  fi
  echo $ver
  echo $old_ver
done

