#!/bin/bash
if [ -z $1 ]; then
  echo "No version provided. Exiting."
  exit 1
fi

ver=$1
# XXX This will fail on devel releases
oldver=`bc <<< "scale=4; ${ver}-0.020"`
old="${prog}-${oldver}-*rpm"

# Release
if [ -z $2 ]; then
  rel=1
else
  rel=$2
fi

prog=usermin
rpmname=${prog}-${ver}-${rel}

# RPM
# RPM
cd ${HOME}/result/vm/6/universal
curl -L -O https://download.webmin.com/devel/rpm/${rpmname}.noarch.rpm
rm -f ${HOME}/result/vm/6/universal/$old
sign-with vm6 ${rpmname}.noarch.rpm
cp ${rpmname}.noarch.rpm ${HOME}/result/vm/6/gpl/universal
rm -f ${HOME}/result/vm/6/gpl/universal/$old
cp ${rpmname}.noarch.rpm ${HOME}/result/vm/7/gpl/rpm/noarch
sign-with vm7 ${HOME}/result/vm/7/gpl/rpm/noarch/${rpmname}.noarch.rpm
rm -f ${HOME}/result/vm/7/gpl/rpm/noarch/$old
cp ${rpmname}.noarch.rpm ${HOME}/result/vm/7/pro/rpm/noarch
sign-with vm7 ${HOME}/result/vm/7/pro/rpm/noarch/${rpmname}.noarch.rpm
rm -f ${HOME}/result/vm/7/pro/rpm/noarch/$old

# tarball
cd ${HOME}/result/vm/6/wbm
curl -L -O https://download.webmin.com/devel/tarballs/${prog}-${ver}.tar.gz
rm -f ${prog}-${oldver}.tar.gz
cd ${HOME}/result/vm/6/gpl/wbm
ln -s ../../wbm/${prog}-${ver}.tar.gz
del-broken-links
for vmver in 7; do
  cd ${HOME}/result/vm/$vmver/wbm
  rm -f ${prog}-${oldver}.tar.gz
  ln -s ../../6/wbm/${prog}-${ver}.tar.gz
  del-broken-links
  cd ${HOME}/result/vm/$vmver/gpl/wbm
  rm -f ${prog}-${oldver}.tar.gz
  ln -s ../../../6/gpl/wbm/${prog}-${ver}.tar.gz
  del-broken-links
done

# Deb
cd ${HOME}/deb-tmp
curl -L -O https://download.webmin.com/devel/deb/${prog}_${ver}_all.deb

aptly repo add virtualmin-universal ${prog}_${ver}_all.deb
aptly repo add virtualmin-gpl-universal ${prog}_${ver}_all.deb
aptly repo add virtualmin-7-pro ${prog}_${ver}_all.deb
aptly repo add virtualmin-7-gpl ${prog}_${ver}_all.deb
