#!/bin/sh
if [ -z $1 ]; then
  echo "No version provided. Exiting."
  exit 1
fi

ver=$1
# XXX This will fail on devel releases
oldver=`bc <<< "scale=4; ${ver}-0.020"`
if [ -z $2 ]; then
  rel=1
else
  rel=$2
fi

prog=webmin
rpmname=${prog}-${ver}-${rel}

# RPM
cd ${HOME}/result/universal
curl -L -O http://prdownloads.sourceforge.net/webadmin/${rpmname}.noarch.rpm
#old=`repomanage --keep=2 --old . | grep ${prog}`
#rm -f $old
cd ${HOME}/result/gpl/universal
ln -sf ../../universal/${rpmname}.noarch.rpm .
rm -f $old
# Copy to the vm6 repo
cd ${HOME}/result/universal
cp ${rpmname}.noarch.rpm ${HOME}/result/vm/6/universal
cd ${HOME}/result/vm/6/universal
rm -f $old
cd ${HOME}/result/vm/6/gpl/universal
ln -sf ../../universal/${rpmname}.noarch.rpm .
rm -f $old
# Copy to the vm7 repo
cd ${HOME}/result/universal
cp ${rpmname}.noarch.rpm ${HOME}/result/vm/7/pro/rpm/noarch
cd ${HOME}/result/vm/7/pro/rpm/noarch
sign-with vm7 ${rpmname}.noarch.rpm
rm -f $old
cd ${HOME}/result/vm/7/gpl/rpm/noarch
ln -sf ../../../pro/rpm/noarch/${rpmname}.noarch.rpm .
rm -f $old


# tarball
cd ${HOME}/result/wbm
curl -L -O http://prdownloads.sourceforge.net/webadmin/${prog}-${ver}.tar.gz
rm ${prog}-${oldver}.tar.gz
cd ${HOME}/result/gpl/wbm
ln -s ../../wbm/${prog}-${ver}.tar.gz
del-broken-links
for vmver in 6 7; do
  cd ${HOME}/result/vm/$vmver/wbm
  rm -f ${prog}-${oldver}.tar.gz
  ln -s ../../../wbm/${prog}-${ver}.tar.gz
  del-broken-links
  cd ${HOME}/result/vm/$vmver/wbm
  rm -f ${prog}-${oldver}.tar.gz
  ln -s ../../../../gpl/wbm/${prog}-${ver}.tar.gz
  del-broken-links
done

# Deb
cd ${HOME}/result/debian/dists/virtualmin-universal/main/binary-i386
curl -L -O http://prdownloads.sourceforge.net/webadmin/${prog}_${ver}_all.deb
cp ${prog}_${ver}_all.deb ../binary-amd64
rm ${prog}_${oldver}_all.deb
cp ${prog}_${ver}_all.deb ${HOME}/result/gpl/debian/dists/virtualmin-universal/main/binary-i386
cp ${prog}_${ver}_all.deb ${HOME}/result/gpl/debian/dists/virtualmin-universal/main/binary-amd64
cd ../binary-amd64
rm ${prog}_${oldver}_all.deb
cd ${HOME}/result/gpl/debian/dists/virtualmin-universal/main/binary-i386
del-broken-links
cd ${HOME}/result/gpl/debian/dists/virtualmin-universal/main/binary-amd64
del-broken-links

aptly repo add virtualmin-universal ${prog}_${ver}_all.deb
aptly repo add virtualmin-gpl-universal ${prog}_${ver}_all.deb
aptly repo add virtualmin-7-pro ${prog}_${ver}_all.deb
aptly repo add virtualmin-7-gpl ${prog}_${ver}_all.deb
