#!/bin/sh

sig=$1
shift

if [ $sig = "old" ]; then
  echo "Signing with 'old' key"
  rpmsign -D '_gpg_name Virtualmin, Inc. <security@virtualmin.com>' --addsign $@
elif [ $sig = "vm6" ]; then
  echo "Signing with 'vm6' key"
  rpmsign -D '_gpg_name Virtualmin, Inc. (Package signing key for Virtualmin 6) <security@virtualmin.com>' --addsign $@
elif [ $sig = "vm7" ]; then
  echo "Signing with 'vm7' key"
  rpmsign -D '_gpg_name Virtualmin, Inc. (Package signing key for Virtualmin 7) <security@virtualmin.com>' --addsign $@
fi

