#!/bin/sh

# Generates various metadata for yum and wbm universal repos.
# Run after any changes to packages in any universal yum or wbm repo.

basedir="$HOME/result"
cachedir="$HOME/rpmcache"

# metadata repos
distrodirs="universal gpl/universal"

for i in $distrodirs; do
    echo "Working on $basedir/$i"
    # Clean up old packages
    rm $(repomanage --keep=3 --old $basedir/$i)
    del-broken-links
    createrepo -s sha --update -q -c $cachedir/$i $basedir/$i
    #createrepo --deltas --oldpackagedirs $basedir/$i -s sha $basedir/$i
done

# wbm/wbt
cd $basedir/wbm
del-broken-links
./make-updates.pl > updates.txt
./make-versions.pl

# wbm/wbt
cd $basedir/gpl/wbm
del-broken-links
./make-updates.pl > updates.txt
./make-versions.pl

# VM6
basedir="$HOME/result/vm/6"
cachedir="$HOME/rpmcache.vm6"

for i in $distrodirs; do
    echo "Working on $basedir/$i"
    # Clean up old packages
    rm $(repomanage --keep=3 --old $basedir/$i)
    cd "$basedir/$i"
    del-broken-links
    createrepo -q -c $cachedir/$i $basedir/$i
    createrepo -q --deltas --oldpackagedirs $basedir/$i $basedir/$i
done

# Update comps.xml
cd $HOME/src/virtualmin-yum-groups
git pull
# Virtualmin Core
rm $basedir/universal/repodata/*comps*
createrepo -g $HOME/src/virtualmin-yum-groups/virtualmin-core-comps.xml $basedir/universal
createrepo -g $HOME/src/virtualmin-yum-groups/virtualmin-core-comps.xml $basedir/gpl/universal

# wbm/wbt
cd $basedir/wbm
del-broken-links
./make-updates.pl > updates.txt
./make-versions.pl

# wbm/wbt
cd $basedir/gpl/wbm
del-broken-links
./make-updates.pl > updates.txt
./make-versions.pl

updateslib.sh
